// Configurações da aplicação
export const CONFIG = {
    API_URL: 'https://ecopontos-server.onrender.com/dados', // URL da API
    API_TIMEOUT: 5000, // Timeout em milissegundos
    UPDATE_INTERVAL_CONNECTED: 5000, // Intervalo de atualização quando conectado (5 segundos)
    UPDATE_INTERVAL_DISCONNECTED: 10000, // Intervalo de atualização quando desconectado (10 segundos)
    CHART_HISTORY_SIZE: 10, // Número de pontos no gráfico
    CRITICAL_LEVEL: 80 // Nível crítico de enchimento (%)
};

// Traduções
export const translations = {
    pt: {
        title: 'Monitorização em Tempo Real - Enchimento do Ecoponto',
        subtitle: 'Monitorização em Tempo Real',
        status: 'Carregando...',
        averageFill: 'Média de Enchimento',
        mostFull: 'Contentor Mais Cheio',
        lastUpdate: 'Última Atualização',
        realTime: 'Tempo Real',
        monitoring: 'Monitorização ativa',
        autoUpdate: 'Atualização automática',
        yellowLabel: 'Plástico e Metal',
        yellowSubtitle: 'Embalagens e recipientes',
        greenLabel: 'Vidro',
        greenSubtitle: 'Garrafas e frascos',
        blueLabel: 'Papel e Cartão',
        blueSubtitle: 'Jornais e embalagens',
        historyTitle: 'Histórico de Enchimento',
        last24h: 'Últimas 24h',
        footerText: 'Projeto desenvolvido para a Prova de Aptidão Profissional de Maximilian Guimaro',
        themeLight: 'Tema Claro',
        themeDark: 'Tema Escuro',
        language: 'Idioma',
        almostFull: 'está quase cheio!',
        connected: 'Conectado',
        disconnected: 'Desconectado'
    },
    es: {
        title: 'Monitoreo en Tiempo Real - Llenado del EcoPunto',
        subtitle: 'Monitoreo en Tiempo Real',
        status: 'Cargando...',
        averageFill: 'Promedio de Llenado',
        mostFull: 'Contenedor Más Lleno',
        lastUpdate: 'Última Actualización',
        realTime: 'Tiempo Real',
        monitoring: 'Monitoreo activo',
        autoUpdate: 'Actualización automática',
        yellowLabel: 'Plástico y Metal',
        yellowSubtitle: 'Envases y recipientes',
        greenLabel: 'Vidrio',
        greenSubtitle: 'Botellas y frascos',
        blueLabel: 'Papel y Cartón',
        blueSubtitle: 'Periódicos y envases',
        historyTitle: 'Historial de Llenado',
        last24h: 'Últimas 24h',
        footerText: 'Proyecto desarrollado para la Prueba de Aptitud Profesional de Maximilian Guimaro',
        themeLight: 'Tema Claro',
        themeDark: 'Tema Oscuro',
        language: 'Idioma',
        almostFull: '¡está casi lleno!',
        connected: 'Conectado',
        disconnected: 'Desconectado'
    },
    de: {
        title: 'Echtzeit-Überwachung - EcoPunkt-Füllstand',
        subtitle: 'Echtzeit-Überwachung',
        status: 'Laden...',
        averageFill: 'Durchschnittliche Füllung',
        mostFull: 'Vollster Container',
        lastUpdate: 'Letzte Aktualisierung',
        realTime: 'Echtzeit',
        monitoring: 'Aktive Überwachung',
        autoUpdate: 'Automatische Aktualisierung',
        yellowLabel: 'Kunststoff und Metall',
        yellowSubtitle: 'Verpackungen und Behälter',
        greenLabel: 'Glas',
        greenSubtitle: 'Flaschen und Gläser',
        blueLabel: 'Papier und Karton',
        blueSubtitle: 'Zeitungen und Verpackungen',
        historyTitle: 'Füllungsverlauf',
        last24h: 'Letzte 24h',
        footerText: 'Projekt entwickelt für die Berufliche Eignungsprüfung von Maximilian Guimaro',
        themeLight: 'Helles Design',
        themeDark: 'Dunkles Design',
        language: 'Sprache',
        almostFull: 'ist fast voll!',
        connected: 'Verbunden',
        disconnected: 'Getrennt'
    },
    fr: {
        title: 'Surveillance en Temps Réel - Remplissage de l\'EcoPoint',
        subtitle: 'Surveillance en Temps Réel',
        status: 'Chargement...',
        averageFill: 'Remplissage Moyen',
        mostFull: 'Conteneur le Plus Plein',
        lastUpdate: 'Dernière Mise à Jour',
        realTime: 'Temps Réel',
        monitoring: 'Surveillance active',
        autoUpdate: 'Mise à jour automatique',
        yellowLabel: 'Plastique et Métal',
        yellowSubtitle: 'Emballages et contenants',
        greenLabel: 'Verre',
        greenSubtitle: 'Bouteilles et flacons',
        blueLabel: 'Papier et Carton',
        blueSubtitle: 'Journaux et emballages',
        historyTitle: 'Historique de Remplissage',
        last24h: 'Dernières 24h',
        footerText: 'Projet développé pour l\'Épreuve d\'Aptitude Professionnelle de Maximilian Guimaro',
        themeLight: 'Thème Clair',
        themeDark: 'Thème Sombre',
        language: 'Langue',
        almostFull: 'est presque plein !',
        connected: 'Connecté',
        disconnected: 'Déconnecté'
    },
    ja: {
        title: 'リアルタイム監視 - エコポイント充填レベル',
        subtitle: 'リアルタイム監視',
        status: '読み込み中...',
        averageFill: '平均充填率',
        mostFull: '最も満杯のコンテナ',
        lastUpdate: '最終更新',
        realTime: 'リアルタイム',
        monitoring: 'アクティブ監視',
        autoUpdate: '自動更新',
        yellowLabel: 'プラスチック・金属',
        yellowSubtitle: '包装容器',
        greenLabel: 'ガラス',
        greenSubtitle: 'ボトル・容器',
        blueLabel: '紙・段ボール',
        blueSubtitle: '新聞・包装材',
        historyTitle: '充填履歴',
        last24h: '過去24時間',
        footerText: 'Maximilian Guimaroの職業適性試験のために開発されたプロジェクト',
        themeLight: 'ライトテーマ',
        themeDark: 'ダークテーマ',
        language: '言語',
        almostFull: 'がほぼ満杯です！',
        connected: '接続済み',
        disconnected: '未接続'
    }
}; 